version: '3'
services:
  web:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '../src:/app'
    environment:
      - SYMFONY_PROJECT_NAME=bootstrap
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=bootstrap
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=bootstrap